const words = [
"Lấp lánh","Thướt tha","Lộng lẫy","Lưu luyến", "Khắc khoải","Bồi hồi","Dửng dưng","Ngất ngây","Chênh vênh","Lênh đênh","Bập bềnh","Thênh thang","Chới với","Ngỡ ngàng","Ghềnh đá","Thung lũng","Bán đảo",
"Trưởng thành","Trẻ con","Nương rẫy","Vách núi","Hang sâu","Biển cả","Đại dương","Quả xoài","Quả dứa","Quả sồi","Cây thông",
"Quang gánh","Uớc nguyện","Rong rêu","Tảo biển","Chim sâu","Gà rừng","Vịt trời","Cá ngựa","Bạch tuộc","Sứa biển","Bọ ngựa","Bọ hung","Trăn đất",
"Xâu chuỗi","Chim chóc","Phi công","Phóng viên","Kiểm lâm","Diễn giả","Cơm tấm","Bánh xèo","Bánh cuốn","Nem rán","Dưa hành","Củ kiệu","Thịt quay","Thịt luộc","Lẩu thái","Trứng chiên","Kem tươi","Nước mía","Bia hơi",
"Bàn ghế","Máy lạnh","Quạt máy","Đũa tre","Khăn tắm","Giấy vệ sinh","Sữa tắm","Gương soi","Phẫn nộ","Căm hờn","Kiêu ngạo","Khoan khoái","Khó chịu","Trống vắng","Hầm xương","Luộc thịt","Dọn dẹp","Giặt giũ","Mua sắm","Pháp luật","Công lý","Quyền lực","Trách nhiệm","Bổn phận","Quyền hạn","Bình đẳng","Bác ái","Hoà bình","Hợp tác","Phát triển","Văn minh","Khoa học","Công nghệ","Thông tin","Truyền thông","Dữ liệu","Máy chủ","Màn hình","Bàn phím","Chuột máy","Tai nghe","Chùa chiền","Cúng bái","Nhang khói","Hương khói","Bùa chú","Duyên phận","Vận may","Điềm báo","Linh hồn","Giông tố","Cuồng phong","Lốc xoáy","Mưa dầm","Sấm chớp","Mây trắng","Nắng vàng","Bầu trời","Ánh nắng","Ánh trăng","Sao băng","Sao chổi","Kháng sinh","Vắc xin","Phẫu thuật","Chẩn đoán","Điều trị","Huyết áp","Tiểu đường","Dị ứng","Trị liệu","Phòng khám","Bóng rỗ","Bóng chuyền","Cầu lông","Quần vợt","Bơi lội","Leo núi","Nhảy dù","Lướt sóng","Trượt băng","Cờ tướng",
"Hoả tốc",
"Bẽn lẽn",
"Phạm pháp",
"Sao chép",
"Truyện tranh","Lương bổng",
"Cơm nguội",
"Công văn","Chủ tịch",
"Lạnh lẽo","Lạnh cóng",
"Gay cấn",
"Chúc mừng",
"Hành nghề","Lành nghề",
"Gà trống","Trống đồng",
"Chung kết","Bán kết","Tứ kết","Vòng loại",
"Mã lực",
"Biên giới","Biên cương","Biên độ","Biên kịch",
"Phán xét","Phán quyết",
"Lưu hương",
"Nồng nặc","Lông vũ",
"Khiêu vũ","Điệu nhảy",
"Tắm gội",
"Trái ô liu",
"Dầu dừa","Kẹo dẻo","Kẹo mút",
"Chảy máu",
"Sinh tồn","Sinh sôi",
"Hương ước","Quy ước",
"Cộng đồng",
"Khuyến khích","Giáo dục",
"Tội phạm",
"Quốc gia",
"Đình chỉ",
"Khám bệnh","Chữa bệnh",
"Thông báo",
"Giới tính",
"Cấu trúc",
"Gia tăng",
"Khả năng",
"Tự nhiên",
"Lững thững",
"Lắc vòng",
"Biến tấu","Biến dị","Biến đổi","Biến chất","Biến tính","Biến thiên","Biến hoá",
"Khủng long",
"Ốc anh vũ",
"Tiến hoá",
"Thoái hoá",
"Thăng chức","Thăng tiến",
"Thành công",
"Thất bại","Thất thoát",
"Thua lỗ","Thua cuộc",
"Chai cồn","Chai kính",
"Cái gương",
"Tấm gương",
"Noi gương",
"Nhân giống","Nhân bản",
"Chiết cành",
"Ghép cành",
"Phân bón",
"Nón cối",
"Xe tăng",
"Đại tướng","Binh nhất","Binh nhì","Trung tướng","Thiếu tá","Thống đốc",
"Vòng eo",
"Thon gọn",
"Gọn gàng",
"Ràng buộc",
"Bóng bay",
"Khí cầu",
"Bâng khuâng",
"Ngổn ngang",
"Lắt léo",
"Tréo ngoe",
"Lác đác",
"Trái nhào",
"Nao núng",
"Côi cút",
"Hẩm hiu",
"Ôi thiu",
"Hỏng hóc",
"Thập thò",
"Thều thào",
"Uyên thâm","Uyên bác",
"Tĩnh mịch",
"Lèo tèo",
"Liêu xiêu",
"Nhí nhố",
"Lố nhố","Lố lăng","Lố bịch",
"Cửa hàng",
"Bệnh viện",
"Thương mại",
"Nhiệt điện","Thủy điện",
"Đập nước",
"Viễn thông",
"Truyền hình",
"Quốc phòng",
"Nghiên cứu",
"Văn chương",
"Nghĩa vụ",
"Đủng đỉnh",
"Đau đớn",
"Đu đưa",
"Đùa giỡn",
"Thiên đình","Thiên lôi",
"Nhân sâm",
"Ngọc bích",
"Bì bõm",
"Thủy triều",
"Nước nông","Nước lớn","Nước ròng","Nước mặn","Nước ngọt","Nước lợ","Nước sâu","Nước giếng","Nước thánh",
"Khua nước",
"Mái dầm","Mái chèo",
"Tay chèo",
"Cạp nong","Cạp nia",
"Cái thúng",
"Lục bình",
"Trôi nổi",
"Tha hương",
"Giấc mơ","Giấc mộng",
"Leng keng",
"Cống rãnh",
"Xếp hình",
"Lưỡi lục",
"Dây câu",
"Thượng hạng",
"Điện trở",
"Cường độ",
"Dông gió",
"Ô uế",
"Oải hương",
"Đậu nành","Đậu tương","Đậu xanh","Đậu đỏ","Đậu trắng","Đậu đen","Đậu hà lan",
"Cổ tích",
"Điển cố","Điển tích",
"Dâng trào",
"Chói lọi",
"Mạng nhện",
"Giáng nhện",
"Ngọc hoàng",
"Trần gian",
"Hấp dẫn",
"Tiểu thuyết","Tiểu thương",
"Tập trung","Tập thể",
"Trào phúng",
"Hào nhoáng",
"Lập phương",  
"Hợp nhất","Hợp đồng",
"Hân hoan","Hân khoái",
"Sầu riêng",
"Hoàng thượng","Hàng hoá","Hàng không",
"Ngũ hành sơn",
"Mặt trăng",
"Trái Đất",
"Yếu đuối",
"Nghi ngờ",
"Phong lan",
"Thủy lợi",
"Dân chúng",
"Mê muội",
"Bún riêu",
"Chăn gối",
"Phấn khích",
"Khiêu khích",
"Đào hoa",
"Biệt tài","Biệt thự",
"Sân vườn",
"Bóng đá","Bóng loáng",
"Cơm sườn",
"Lặng lẽ",
"Cô quạnh",
"Bài hát",
"Máy tính","Máy móc","Máy giặt",
"Trứng gà","Trứng vịt",
"Đại bàng","Chim ưng","Chim sẻ",
"Rùa biển",
"Chung sức",
"Biển Đông",
"Núi cao",
"Vọng lâu",
"Hang động",
"Động đất","Động kinh","Động trời",
"Mây mù",
"Cầu vồng","Cầu treo","Cầu vượt","Cầu khỉ","Cầu nguyện",
"Lay lất",
"Lung linh",
"Huyền bí","Huyền ảo",
"Dung túng",
"Bao che",
"Ngại ngùng",
"Phiền phức","Phiền muộn",
"Chia rẽ",
"Tê tái","Tê giác",
"Cảnh báo",
"Biển báo",
"Cối xay gió",
"Buồn hiu",
"Ốc đảo","Ốc vít",
"Nam thần",
"Thần tượng","Thần thánh","Thần bài",
"Giới hạn","Giới thiệu",
"Tương tác","Tương tư","Tương trợ","Tương cà","Tương thích",
"Sách vở",
"Mưu lược","Mưu mẹo",
"Con giáp","Con vẹt",
"Trùng sinh","Trùng hợp",
"Phản ứng","Phản lực","Phản đối","Phản hồi","Phản chiếu","Phản bội","Phản kích","Phản phệ",
"Thuyền buôn","Thuyền buồm",
"Cướp giật",
"Tiêu điều","Tiêu đề","Tiêu tan",
"Mít ướt",
"Mích lòng",
"Cái kiềng",
"Bộc phát","Bộc bạch",
"Chân thành","Chân tình","Chân thật",
"Nhạc sĩ","Nhạc cụ","Âm nhạc",
"Gia đình","Gia phả","Gia tiên","Gia nhiệt","Gia tốc","Gia cố",
"Nước mắt",
"Gạch ống",
"Cù lao",
"Sông ngòi",
"Chằng chịt",
"Hồng hào","Hồng bao",
"Đồng tiền","Đồng xu","Đồng lòng","Đồng bộ","Đồng thau",
"Tái sinh","Tái diễn",
"Bài học","Bài bạc",
"Tượng đài",
"Kết tinh",
"Tinh thể",
"Thao túng","Thao trường",
"Tàu hoả","Tàu điện","Tàu hủ",
"Bồi dưỡng","Bồi đắp","Bồi bổ",
"Sức khoẻ","Sức mạnh","Sức sống",
"Tâm trạng","Tâm tình",
"Chuyển giao","Chuyển đổi","Chuyển nhượng",
"Xung đột","Xung phong",
"Truyền đạt","Truyền thống",
"Trà sữa","Trà móc câu",
"Lưỡi hái","Lưỡi liềm","Lưỡi câu",
"Bánh xe","Bánh pía","Bánh da lợn","Bánh tiêu","Bánh chuối","Bánh kẹp",
//cá
"Cá lóc","Cá rô phi","Cá chim","Cá linh","Cá nóc","Cá trê","Cá điêu hồng","Cá mè trắng","Cá sấu","Cá nướng","Cá mập","Cá chuồn",
//động vật
"Con bướm","Con dơi","Hươu cao cổ","Gấu trúc","Chuột túi","Con cáo","Tinh tinh","Linh dương","Linh cẩu","Linh miêu","Con muỗi","Lăng quăng","Bọ gậy","Rệp sáp","Chàng hiu","Cóc tía","Lạc đà","Con sóc","Con mèo","Con tê tê","Đà điểu",
"Báo thức",
"Hoan hỉ",
"Vấn vương",
"Vết thương",
"Tổn thương",
"Quãng đường",
"Tảo tần",
"Buôn bán",
"Buồng giam",
"Ngục tối",
"Vách đá",
"Vô tuyến","Vô hình","Vô biên",
"Sân bay",
"Hải tặc","Hải quan","Hải quân",
"Hí hửng",
"Thị trường",
"Hạt nhân",
"Nhân quả","Nhân tài","Nhân chứng","Nhân dân","Nhân tiện",
"Quỹ đen",
"Cải cúc","Cải thìa","Cải bó xôi","Cải xanh","Cải ngọt",
"Tần ô",
"Nguyên phân","Nguyên nhân",
"Bóc lột",
"Châm chế","Châm chọc",
"Đìu hiu",
"Rượu cần",
"Bình thường","Bình tĩnh","Bình ổn","Bình minh",
"Hoàng hôn",
"Dế choắt","Dế chũi",
"Chuột chũi",
"Tài lanh",
"Khôn lỏi","Khôn ngoan",
"Hậu quả","Hậu phương","Hậu trường",
"Đạo diễn","Diễn viên","Quần chúng",
"Tổng thống","Tổng cộng",
"Khởi nghĩa",
"Chiến tranh","Chiến thắng","Chiến lược",
"Kế sách",
"Quỹ đạo",
"Hành tinh","Hành chính",
"Nhà nước",
"Ngân hàng","Ngân sách",
"Cao thượng",
"Tối hậu thư",
"Yêu kiều",
"Mỏng manh",
"Phù du",
"Lãng khách",
"Thích khách",
"Quyết định",
"Đậm đà",
"Màu sắc",
"Kinh nghiệm","Kinh thành","Kinh hãi",
"Thế vận hội",
"Đấu trường",
"Khoai môn",
"Mảnh khảnh",
"Thủy tinh",
"Ruột thừa",
"Kiến tạo","Kiến thức",
"Thừa kế",

"Nham thạch","Nham hiểm",
"Trung vệ","Tiền đạo","Cầu thủ","Thủ môn",
"Cấm đoán",

"Tôm tích","Tôm hùm",
"Cua biển",
"Bồi bàn",
"Phục vụ",
"Công khai",
"Minh bạch",
"Chấm dứt",
"Đường xá",
"Đường thủy",
"Tâm địa",
"Thành thật",
"Xiêu vẹo",
"Xăm trổ",
"Vội vàng",
"Vùng vẫy",
"Vòi rồng",
"Quyên góp","Uyên ương",
"Ung dung",
"Phóng thanh","Phóng điện","Phóng khoáng",
"La bàn","Bàn là",
"Lộc vừng",
"Chào mào",
"Trừng trị",
"Nhanh nhẹn","Nhục nhã",
"Bão tố",
"Bền vững",
"Xê dịch",
"Mạt chược",
"Trầm hương",
"Súc tích",
"Xúc xích",
"Bông tai",
"Khuyên tai",
"Trong sạch",
"Chụp hình",
"Nhiếp ảnh",
"Thiên thạch","Thiên phú","Thiên bẩm",
"Cổ phiếu","Trái phiếu",
"Mông lung",
"Sát thủ",
"Hình chóp","Hình thoi","Hình tam giác",
"Dăm bụt",
"Phương hướng",
"Hiện trường",
"Kinh hoàng",
"Miễn nhiễm",
"Bạch cầu",
"Xuất chung","Xuất khẩu",
"Đàn hồi",
"Vận chuyển",
"Tuyệt vời",
"Chuẩn mực",
"Cam thảo",
"Thảo mộc",
"Rau tiến vua","Rau muống","Rau răm",
"Ong vò vẽ","Ong bần","Ong mật",
"Bướm đêm",
"Giao thông","Giao điểm","Giao dịch",
"Trúng phóc","Trúng đích","Trúng thưởng",
"Độc đắc","Độc hại","Độc quyền",
"Suối nguồn",
"Nguồn nước",
"Rừng cây",
"Nhiệt đới","Nhiệt độ","Nhiệt hạch",
"Bãi cát","Bãi biển",
"Rặng đá ngầm",
"Sương mù",
"Cánh đồng",
"Đầm lầy","Đầm thắm",
"Thảo nguyên",
"Cao nguyên",
"Ngẩn ngơ",
"Xao xuyến",
"Tỉnh táo","Tỉnh lị","Tỉnh thành",
"Mẫn cảm",
"Kính lúp",
"Máy chiếu",
"Mặt phẳng",
"Kính hiển vi",
"Canh chua",
"Thịt kho",
"Sữa tươi","Sữa chua",
"Bánh mứt",
"Kẹo dừa","Kẹo đường",
"Nhím gai",
"Gió bấc","Gió chướng","Gió heo may",
"Mưa phùng",
"Trăng khuyết","Trăng non","Trăng tròn",
"Hội chợ",
"Thư pháp",
"Múa rối",
"Con tò he",
"Phong tục",
"Xương cốt",
"Sườn xám","Sườn non",
"Cốt lết",
"Nạm bò",
"Sừng sững","Sừng trâu",
"Chui rúc",
"Cặm cuội",
"Lê thê",
"Luộm thuộm",
"Nháo nhào",
"Bổ nhào",
"Phỉ báng",
"Người hầu",
"Cương vị","Cương trực","Cương thi",
"Cường đạo",
"Bênh vực",
"Chèo kéo","Chèo xuồng",
"Quê hương",
"Bát ngát",
"Cực quang",
"Nguyền rủa",
"Băng tuyết",
"Kỷ băng hà",
"Băng trôi",
"Chim cánh cụt",
"Gấu bắc cực",
"Mãng xà","Mãng cầu",
"Hoa lài","Hoa hồng",
"Cẩm tú cầu",
"Căn chỉnh",
"Thường trực",
"Trung ương",
"Tức tối",
"Vẻ vang",
"Danh dự","Danh tiếng","Danh vọng","Danh từ",
"Dõng dạc",
"Kiêu hãnh",
"Hãnh diện",
"Tre nứa",
"Lên men",
"Vi sinh vật","Vi trùng",
"Thanh trừng","Thanh trùng",
"Tuyệt chủng",
"Tiệt trùng",
"Xích đu",
"Dây xích",
"Xích mích",
"Từ điển",
"Điển hình",
"Kim loại",
"Giác ngộ","Giác hơi",
"Ngủ ngon",
"Vàng bạc",
"Kim cương",
"Cẩm thạch",
"Khoáng sản",
"Than hoạt tính",
"Kem đánh răng",
"Ổi sẻ",
"Hành phi",
"Khoai lang",
"Phòng ốc",
"Chữa cháy",
"Hoả hoạn",
"Ấu trùng",
"Con nhộng",
"Tơ tằm",
"Vải lụa",
"Keo sơn",
"Phí phạm",
"Nghiêng ngã",
"Trôi dạt",
"Dạt dào",
"Hoang dã","Hoang mạc",
"Ngư dân",
"Mực nang",
"Nhum biển",
"Hải quỳ","Hải sâm",
"Đạm bạc",
"Bói toán",
"Rạng ngời","Rạng đông",
"Lạng choạng",
"Chặng đường",
"Sản phẩm","Sản lượng",
"Cao nhân",
"Ứng dụng",
"Sát hạch",
"Sa hình",
"Lưu huỳnh",
"Phốt pho",
"Chủ quyền",
"Thống nhất",
"Tối thiểu",
"Lương bổng",
"Điều kiện",
"Phiên toà",
"Phiêu lưu",
"Hành trình",
"Giản dị",
"Thiên vị",
"Chí công",
"Hoà thuận",
"Việt vị",
"Túc cầu",
"Ngưng đọng",
"Sương sáo",
"Dương cầm",
"Nhã nhặn",
"Khinh suất",
"Bộp chộp",
"Lục đục",
"Khoan dung","Khoan hồng",
"Độ lượng",
"Lượng giác",
"Âm dương","Âm trầm","Âm bổng","Âm thanh","Âm điệu",
"Ly tán","ly biệt",
"Lụy tình",
"Liên lụy",
"Chống đối",
"Bồng bềnh",
"Thương nhân",
"Gian manh","Gian xảo","Gian thương","Gian dối","Gian lận",
"Giải thoát","Giải thích","Giải tích","Giải bày",
"Giảy nảy",
"Khốn khiếp","Khốn khổ","Khốn đốn",
"Nhịp điệu","Nhịp tim",
"Lai căng","Lai lịch",
"Lươn điện","Lươn lẹo",
"Dũng cảm",
"Thói quen",
"Côn đồ",
"Đồng phạm",
"Mốc nối",
"Liên kết","Liên kích",
"Gừng cay",
"Muối mặn",
"Sấm rền",
"Phương pháp",
"Chủng tộc","Chủng loại",
"Cà cuống",
"Chim chóc",
"Cây bàng",
"Mắm ruốc","Mắm tôm","Mắm nêm",
"Bột giặt","Bột mì",
"Mì vắt","Mì gói","Mì sợi","Mì ăn liền",
"Chanh dây",
"Móng tay",
"Ớt xiêm","Ớt hiểm",
"Dừa sáp",
"Sát vách",
"Bôn ba",
"Tứ phương",
"Phố phường",
"Kiều diễm",
"Đua thuyền",
"Chim yến",
"Xà phòng",
"Dịch hạch","Dịch bệnh","Dịch tả",
"Sốt rét","Sốt cao",
"Sỏi thận",
"Long cung",
"Thông minh",
"Cà kheo",
"Quấy rối","Quấy nhiễu",
"Nhiễu loạn",
"Cái phễu",
"Nhỏ giọt",
"Thịt bằm",
"Vùng đất",
"Địa danh",
"Anh hùng",
"Xuất chúng",
"Trung trực","Trung thành",
"Huấn luyện",
"Khoe mẽ",
"Khô khan",
"Tối giản",
"Kiềm chế",
"Cá lìm kiềm",
"Que diêm",
"Tuần tra",
"Hải sản",
"Sung túc",
"Chuông gió",
"Bánh kem",
"Đồng loã",
"Truy nã",
"Thất thần",
"Con người",
"Ngựa vằn",
"Hạnh nhân",
"Hạt điều",
"Tịnh tâm",
"Mãn nguyên",
"Tâm hồn",
"Dĩ vãng",
"Quá khứ",
"Quá quắt",
"Cam quýt",
"Phất trần",
"Sắt thép",
"Bê tông",
"Đường đất","Đường nâu","Đường cát",
"Núi đá vôi",
"Ống tiêm",
"Kim tiêm",
"Phi tiêu","Phi trường",
"Hợp tình",
"Lý thuyết",
"Thực hành",
"Dẫn chứng","Chứng cứ",
"Nghị luận",
"Luận văn",
"Triết học",
"Bình hoa",
"Phóng cao",
"Súng đạn",
"Lựu đạn",
"Bom khói",
"Thiêu đốt",
"Liên hoàn","Liên thủ",
"Mỹ nhân",
// === CÁC TỪ MỚI THÊM VÀO ===
"Bút chì","Bút mực","Thước kẻ","Cục tẩy","Hộp bút","Cặp sách","Bảng đen","Phấn trắng","Giấy nháp","Sổ tay","Kẹp giấy","Bấm ghim","Băng keo","Hồ dán","Con dấu","Bao thư","Lịch bàn",
"Bàn tay","Bàn chân","Ngón tay","Ngón chân","Đầu gối","Khuỷu tay","Bắp tay","Bắp chân","Lông mày","Lông mi","Mí mắt","Vành tai","Dái tai","Cuống họng","Xương sườn","Mạch máu","Dây thần kinh","Làn da","Mái tóc","Hàm răng","Nướu răng","Lưỡi gà",
"Chạy bộ","Đi bộ","Đạp xe","Lái xe","Sửa xe","Bơm xe","Rửa xe","Tập bơi","Nhảy dây","Kéo co","Đá cầu","Bắn bi","Thả diều","Trồng cây","Tưới cây","Hái quả","Bắt cá","Câu cá","Lặn biển","Trượt tuyết","Trượt patin","Cắm trại","Nấu ăn","Rửa bát","Quét dọn","Lau bàn","Xếp quần áo","Phơi đồ","Gấp mền","Thay ga","Lau kính","Đổ rác",
"Bánh mì","Bánh bao","Bánh giò","Bánh rán","Bánh trôi","Bánh chay","Chè bưởi","Chè thái","Chè bắp","Chè khoai","Kem ốc quế","Kem que","Sữa đậu nành","Sữa bắp","Nước ép","Sinh tố","Trái cây","Mứt dừa","Mứt gừng","Ô mai","Sấu dầm","Cóc dầm","Gỏi đu đủ","Gỏi xoài","Bò bía","Bì cuốn","Cháo lòng","Cháo gà","Cháo cá","Miến gà","Hủ tiếu","Bánh ướt","Bánh bèo","Bánh nậm","Bánh ít","Bánh tày","Cơm lam","Xôi vò","Xôi đậu","Xôi thịt","Bánh bột lọc",
"Áo dài","Áo sơ mi","Áo thun","Quần tây","Quần jean","Quần short","Váy xòe","Áo khoác","Áo mưa","Áo ấm","Nón lá","Mũ bảo hiểm","Mũ len","Khăn quàng","Khăn len","Tất vớ","Giày da","Giày vải","Dép lào","Dép tổ ong","Guốc mộc","Dây nịt","Cà vạt","Nơ bướm","Kẹp tóc","Dây buộc tóc","Bờm tóc",
"Phòng khách","Phòng ngủ","Phòng tắm","Nhà bếp","Phòng ăn","Phòng thờ","Phòng đọc sách","Mái nhà","Cửa sổ","Cửa chính","Cửa hậu","Hành lang","Cầu thang","Bậc thang","Lan can","Sân thượng","Ban công","Giếng trời","Ao cá","Hòn non bộ","Mái hiên","Hiên nhà","Cổng nhà","Hàng rào","Lối đi","Sàn gỗ","Gạch bông","Trần nhà",
"Giáo viên","Học sinh","Sinh viên","Y tá","Hộ lý","Nha sĩ","Dược sĩ","Luật sư","Thẩm phán","Công an","Bộ đội","Lính cứu hỏa","Tài xế","Đầu bếp","Phụ bếp","Nhân viên","Quản lý","Giám đốc","Thư ký","Kế toán","Kiểm toán","Thu ngân","Bảo vệ","Lao công","Tạp vụ","Pha chế","Người mẫu",
"Xe máy","Xe đạp","Ô tô","Xe buýt","Xe khách","Xe tải","Xe lam","Xe ôm","Tàu thủy","Máy bay","Trực thăng","Ca nô","Xuồng máy","Thuyền thúng","Xe lăn","Xe cút kít","Xe bò","Xe ngựa",
"Dễ thương","Đáng yêu","Đáng ghét","Khó ưa","Dễ mến","Thân thiện","Cởi mở","Ít nói","Lạnh lùng","Nóng nảy","Điềm đạm","Chín chắn","Ngây thơ","Hồn nhiên","Tinh nghịch","Nghịch ngợm","Lười biếng","Siêng năng","Cần cù","Chịu khó","Thông minh","Sáng dạ","Ngu ngốc","Đần độn","Khờ khạo","Nhát gan","Gan dạ","Hèn nhát","Trung thực","Dối trá","Xảo quyệt","Hiền lành","Dữ tợn","Tốt bụng","Xấu bụng","Keo kiệt","Hào phóng","Ích kỷ","Vị tha","Bao dung","Tham lam","Đố kỵ","Ghen tuông","Kiên nhẫn","Nóng vội",
"Ráng chiều","Hừng đông","Trời đất","Gió mây","Mưa rào","Mưa phùn","Mưa đá","Tuyết rơi","Băng giá","Sương muối","Sương sớm","Nắng gắt","Nắng oi","Gió lốc","Gió mùa","Gió nam","Gió nồm","Biển lặng","Sóng lớn","Sóng thần","Triều cường","Triều kiệt","Nước xoáy","Vực sâu","Hẻm vực","Đồi trọc","Rừng rậm","Rừng thưa",
"Bài ca","Tiếng hát","Giọng ca","Ca khúc","Sáo trúc","Đàn bầu","Đàn tranh","Đàn nguyệt","Đàn tì bà","Ghi ta","Vĩ cầm","Phong cầm","Trống cơm","Trống trường","Thanh la","Mõ làng","Chiêng đồng","Cồng chiêng","Múa quạt","Múa lân","Múa sạp","Hát chèo","Hát tuồng","Cải lương","Hát ru","Hát then","Hát xoan",
"Hình học","Đại số","Số học","Phân số","Hỗn số","Số nguyên","Số thực","Phép tính","Cộng trừ","Nhân chia","Lũy thừa","Phương trình","Hóa học","Vật lý","Sinh học","Thiên văn","Địa chất","Khí tượng","Hải dương","Giải phẫu","Di truyền","Tế bào","Vi khuẩn","Nguyên tử","Phân tử","Điện tử",
"Bài thơ","Câu văn","Áng văn","Thi phẩm","Truyện ngắn","Tác giả","Độc giả","Bản thảo","In ấn","Thư viện","Hiệu sách","Chính tả","Ngữ pháp","Dấu câu","Chữ cái","Mẫu tự","Vần điệu","Ca dao","Tục ngữ","Thành ngữ",
"Hạnh phúc","Khổ đau","Vất vả","Gian nan","Thử thách","Cơ hội","May mắn","Rủi ro","Tai nạn","Tai ương","Họa phúc","Ân tình","Oán hận","Thù hận","Công ơn","Nghĩa tình","Tình thương","Lòng tốt","Việc thiện","Việc ác","Công bằng","Dân chủ",
"Bóng ném","Bi lắc","Leo dây","Cờ gánh","Cờ úp","Đánh đáo","Đánh khăng","Bắn ná","Đua ngựa","Đua chó",
"Tín hiệu","Ăng ten","Vệ tinh","Trạm vũ trụ","Tàu vũ trụ","Người máy","Rô bốt","Cảm biến","Mạch điện","Bóng đèn","Công tắc","Ổ cắm","Phích cắm","Dây điện","Chập điện","Rò điện","Tiết kiệm","Lãng phí","Bảo vệ","Phá hoại","Xây dựng","Kiến thiết","Quy hoạch","Đô thị","Nông thôn","Thành thị","Miền núi","Đồng bằng","Ven biển","Hải đảo",
// === CÁC TỪ ÍT PHỔ BIẾN ===
"Lẩn thẩn","Lẩm cẩm","Lệt bệt","Lụ khụ","Lờ đờ","Lừ đừ","Ngắc ngoải","Ngồm ngoàm","Nhăn nhó","Nhấp nhô","Nhởn nhơ","Nhem nhuốc","Nhễ nhại","Nhí nhảnh","Nhố nhăng","Nườm nượp","Quạu quọ","Què quặt","Rầu rĩ","Rề rà","Rệu rã","Rôm rả","Run rẩy","Tất tả","Tất bật","Tần ngần","Tần tiện","Tất tưởi","Thầm thì","Thầm thĩ","Thơ thẩn","Thờ ơ","Thù lù","Thụt thò","Tí tách","Tí teo","Tỉ tê","Tị nạnh","Toe toét","Tơi tả","Tưng bừng","Tươm tất","Vất vưởng","Vênh váo","Ve vẩy","Vội vã","Vồ vập","Vụng về","Xanh xao","Xào xạc","Xấp xỉ","Xập xệ","Xấu xí","Xì xào","Xì xụp","Xoay xở","Xơ xác","Xuề xoà","Xúng xính",
"Bằng hữu","Cố tri","Cự phách","Danh gia","Danh sư","Đạo tặc","Đồ thư","Đồng liêu","Gia pháp","Giai nhân","Hà khắc","Hải cẩu","Hàn lâm","Hiệp khách","Hí viện","Huyết thống","Khai phá","Khất thực","Kỳ tài","Lão gia","Lão luyện","Liên bang","Nhân kiệt","Pháp trường","Phi nghĩa","Phong lưu","Quân vương","Quốc sắc","Sầu muộn","Siêu việt","Tài hoa","Tâm phúc","Thi sĩ","Thổ phỉ","Thư đồng","Tiên tri","Tiều phu","Tín đồ","Trí thức","Trọc phú","Văn hào","Viễn xứ","Vô thường","Võ tướng","Xướng ca","Y sư",
"Bìm bịp","Bồ câu","Cạy cục","Chảnh chọe","Chèo queo","Chình ình","Cỏn con","Cù lần","Dãi dầu","Dở dang","Đực rựa","Ghẻ lạnh","Hằn học","Hấp tấp","Hì hục","Híp mắt","Hiu quạnh","Hò hét","Hờ hững","Hục hặc","Hừng hực","Kèo nèo","Khệnh khạng","Khò khè","Khù khờ","Lạch bạch","Lam lũ","Lào thào","Le te","Lè nhè","Lép xép","Lẹt đẹt","Lêu lổng","Linh tinh","Lô nhô","Lồ lộ","Lơ mơ","Lơ ngơ","Lởm chởm","Lù đù","Lục cục","Lưng chừng","Lừng lững","Mập mờ","Mếu máo","Mơ màng","Mờ mịt","Mù mịt","Mừng rỡ","Ngả nghiêng","Nghênh ngang","Nghi ngút","Ngo ngoe","Nhằng nhịt","Nhấp nháy","Nhâm nhi","Nhập nhằng","Nhẹ tênh","Nhức nhối","Phì phà",Phơi phới","Rệu rạo",
"Chèo bẻo","Chìa vôi","Chiền chiện","Chích chòe","Cuốc cuốc","Đa đa","Đom đóm","Le le","Lích chích","Nhông nhông","Sáo sậu","Tắc kè","Tích tắc","Tò vò","Tu hú","Vạc vạc",
"Bần bật","Chan chát","Chèm bẹp","Chình ình","Đành đạch",
// === CÁC TỪ DỄ MỚI THÊM ===
"Ông bà","Cha mẹ","Anh em","Chị em","Vợ chồng","Con cháu","Họ hàng","Hàng xóm","Bạn bè","Thầy cô","Học trò","Bạn học","Đồng nghiệp",
"Anh trai","Em gái","Ông nội","Bà ngoại","Chú bác","Cậu mợ","Cô dì","Cháu chắt",
"Xe cộ","Đường sá","Cây cỏ","Hoa lá","Rau xanh","Trái chín","Quả ngọt","Thịt cá","Cơm canh","Áo quần","Giày dép","Mũ nón","Túi xách","Ví tiền","Điện nước","Nhà cửa","Giấy bút","Bút vở",
"Tủ lạnh","Bếp ga","Nồi cơm","Chảo rán","Dao kéo","Muỗng nĩa","Bát đĩa","Ly tách","Ấm chén","Đồng hồ","Điện thoại","Máy ảnh","Loa đài",
"Cà phê","Trà đá","Nước cam","Nước dừa","Nước chanh","Sữa đậu","Bia lon","Rượu vang",
"Phở bò","Phở gà","Bún bò","Bún chả","Cơm rang","Cơm chiên","Cháo trắng","Cháo thịt","Mì xào","Bánh canh","Bánh đa","Kem dừa","Kem chuối","Mứt dâu","Mứt me",
"Chó mèo","Gà vịt","Trâu bò","Ngựa lừa","Cá vàng","Cá chép","Tôm tép","Cua cá","Ốc sên","Rắn rết","Kiến gián",
"Đánh răng","Rửa mặt","Chải đầu","Đi học","Đi làm","Đi chợ","Nấu cơm","Rửa chén","Quét nhà","Lau nhà","Giặt đồ","Ủi đồ","Xem phim","Nghe nhạc","Đọc sách","Viết bài","Học bài","Làm bài","Tập vẽ","Tập hát",
"Xinh đẹp","Tốt lành","Vui vẻ","Buồn bã","Sợ hãi","Lo lắng","Bình yên","Yên tĩnh","Mát mẻ","Nóng bức","Lạnh buốt",
"Cuộc sống","Tình yêu","Tình bạn","Trường lớp","Thuốc men","Tiền bạc","Sức khỏe","Bệnh tật",
"Trời nắng","Trời mưa","Mây đen","Gió thổi","Sấm sét","Mưa bão","Bão lũ",
];