const words = [

"Đủng đỉnh",
"Trần gian",
"Hấp dẫn",
"Tiểu thuyết",
"Tập trung","Tập thể",
"Trào phúng",
"Hào nhoáng",
"Lập phương",  
"Hợp nhất","
"Hân hoan",
"Sầu riêng",
"Hoàng thượng",
"Ngũ hành sơn",
"Mặt trăng",
"Trái Đất",
"Yếu đuối",
"Nghi ngờ",
"Phong lan",
"Thủy lợi",
"Dân chúng",
"Mê muội",
"Bún riêu",
"Chăn gối",
"Phấn khích",
"Khiêu khích",
"Đào hoa",
"Biệt tài","Biệt thự",
"Sân vườn",
"Bóng đá",
"Cơm sườn",
"Lặng lẽ",
"Cô quạnh",
"Bài hát",
"Máy tính","Máy móc","Máy giặt",
"Trứng gà","Trứng vịt",
"Đại bàng","Chim ưng","Chim sẻ","Con vẹt",
"Cá mập","Rùa biển",
"Chung sức",
"Đồng lòng",
"Biển Đông",
"Núi cao",
"Vọng lâu",
"Hang động",
"Động đất","Động kinh","Động trời",
"Mây mù",
"Cầu vồng","Cầu treo","Cầu vượt","Cầu khỉ",
"Lay lất",
"Lung linh",
"Huyền bí","Huyền ảo",

];